//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCookingKR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int Id { get; set; }
        public int IdRecipe { get; set; }
        public int IdIngredient { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
