//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCookingKR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Note = new HashSet<Note>();
            this.RecipeIngredient = new HashSet<RecipeIngredient>();
        }
    
        public int IdRecipe { get; set; }
        public int IdRecipeCategory { get; set; }
        public string Name { get; set; }
        public string Preparation { get; set; }
        public string Photo { get; set; }
        public int IdCreator { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Creator Creator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        public virtual RecipeCategory RecipeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeIngredient> RecipeIngredient { get; set; }
    }
}
